#!/usr/bin/env python3
"""
FastAPI server to serve performance reports.
Run with: uvicorn report_server:app --reload --host 0.0.0.0 --port 8000
"""

import os
from pathlib import Path
from datetime import datetime
from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse, FileResponse
from fastapi.staticfiles import StaticFiles
import aiofiles

app = FastAPI(title="Trading Report Server", description="Serves generated performance reports")

# Configuration
REPORTS_BASE = Path("discovery_outputs")
STATIC_DIR = Path("static_reports")  # For any custom static files

# Ensure static directory exists
STATIC_DIR.mkdir(exist_ok=True)

def find_all_report_files() -> list:
    """Recursively find all HTML report files in discovery_outputs."""
    report_files = []
    if not REPORTS_BASE.exists():
        return report_files
    
    for html_file in REPORTS_BASE.rglob("*.html"):
        # Exclude template files (if any)
        if "template" in html_file.name.lower():
            continue
        rel_path = html_file.relative_to(REPORTS_BASE)
        report_files.append({
            "path": str(rel_path),
            "name": html_file.name,
            "run_dir": html_file.parent.name,
            "modified": datetime.fromtimestamp(html_file.stat().st_mtime).strftime("%Y-%m-%d %H:%M:%S"),
            "size_kb": round(html_file.stat().st_size / 1024, 1)
        })
    # Sort by modification time, newest first
    report_files.sort(key=lambda x: x["modified"], reverse=True)
    return report_files

@app.get("/", response_class=HTMLResponse)
async def index():
    """List all available report HTML files."""
    reports = find_all_report_files()
    
    html_content = """
    <!DOCTYPE html>
    <html>
    <head>
        <title>Trading Reports</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; background: #f5f7fa; }
            h1 { color: #333; }
            table { width: 100%; border-collapse: collapse; background: white; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
            th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
            th { background-color: #4CAF50; color: white; }
            tr:hover { background-color: #f5f5f5; }
            a { text-decoration: none; color: #2196F3; }
            a:hover { text-decoration: underline; }
            .badge { background: #e0e0e0; padding: 3px 8px; border-radius: 12px; font-size: 12px; }
        </style>
    </head>
    <body>
        <h1>📊 Trading Performance Reports</h1>
        <p>Generated reports from the analytics pipeline.</p>
        <table>
            <thead>
                <tr>
                    <th>Report Name</th>
                    <th>Run Directory</th>
                    <th>Last Modified</th>
                    <th>Size (KB)</th>
                </tr>
            </thead>
            <tbody>
    """
    
    for report in reports:
        html_content += f"""
        <tr>
            <td><a href="/reports/{report['path']}">{report['name']}</a></td>
            <td>{report['run_dir']}</td>
            <td>{report['modified']}</td>
            <td>{report['size_kb']}</td>
        </tr>
        """
    
    if not reports:
        html_content += "<tr><td colspan='4'>No HTML reports found. Run stg_6_analytics.py first.</td></tr>"
    
    html_content += """
            </tbody>
        </table>
        <p style="margin-top: 20px; font-size: 12px; color: #666;">
            Reports are served from <code>discovery_outputs/</code> directory.<br>
            Generated by Agentic Trading System.
        </p>
    </body>
    </html>
    """
    return HTMLResponse(content=html_content)

@app.get("/reports/{path:path}")
async def serve_report(path: str):
    """Serve a specific HTML report file."""
    file_path = REPORTS_BASE / path
    # Security: ensure path is within REPORTS_BASE
    try:
        file_path = file_path.resolve()
        REPORTS_BASE.resolve().parent  # just to get base
        if not str(file_path).startswith(str(REPORTS_BASE.resolve())):
            raise HTTPException(status_code=403, detail="Forbidden")
    except Exception:
        raise HTTPException(status_code=403, detail="Invalid path")
    
    if not file_path.exists() or not file_path.is_file():
        raise HTTPException(status_code=404, detail="Report not found")
    
    # Only serve HTML files (for security)
    if file_path.suffix.lower() != '.html':
        raise HTTPException(status_code=403, detail="Only HTML files are served")
    
    return FileResponse(file_path, media_type="text/html")

@app.get("/latest", response_class=HTMLResponse)
async def latest_report():
    """Redirect to the most recent report."""
    reports = find_all_report_files()
    if not reports:
        return HTMLResponse(content="<h2>No reports found</h2>", status_code=404)
    latest = reports[0]['path']
    return HTMLResponse(content=f"""
    <html><head><meta http-equiv="refresh" content="0; url=/reports/{latest}"></head>
    <body>Redirecting to <a href="/reports/{latest}">latest report</a>...</body>
    </html>
    """)

@app.get("/health")
async def health():
    return {"status": "ok", "reports_found": len(find_all_report_files())}

if __name__ == "__main__":
    import uvicorn
    print("Starting report server at http://localhost:8000")
    print("Open http://localhost:8000 to see available reports")
    print("Or go directly to latest: http://localhost:8000/latest")
    uvicorn.run(app, host="0.0.0.0", port=8000)